name: create pr
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Make change
        run: echo "Hello world txt (after dropping create/approve PRs flag)" > hello.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
