name: create pr
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Approve Pull Request
        run: gh pr review --approve 12
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
