name: secrets
on: [push, pull_request]

permissions: {}

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: |
          echo $THESECRET | base64 | base64
          echo "this is the secret: $THESECRET (redacted by GitHub)"
          echo not in env: ${{ secrets.ANOTHER_SECRET }}
        env:
          THESECRET: ${{ secrets.HELLOWORLD }}
      - uses: mscoutermarsh/ascii-art-action@master
        with:
          text: ${{ secrets.HELLOWORLD }}
