name: secrets
on: [push, pull_request]

permissions:
  contents: write

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: |
          echo HI FROM A FORK!
          echo $THESECRET | base64 | base64
          echo "this is the secret: $THESECRET (redacted by GitHub)"
        env:
          THESECRET: ${{ secrets.HELLOWORLD }}
      - uses: mscoutermarsh/ascii-art-action@master
        with:
          text: ${{ secrets.HELLOWORLD }}
